version: "3.9"
services:
  # web:
  #   container_name: web
  #   build: ${PATH_REQ}nginx/
  #   networks:
  #     - docker-network
  #   restart: always
  #   ports:
  #     - $HOST_HTTP:$CONTAINER_HTTP
  #     - $HOST_HTTPS:$CONTAINER_HTTPS
  #   command: nginx -g "daemon off;"
  db:
    container_name: db
    build: ${PATH_REQ}mariadb/
    networks:
      - docker-network
    restart: always
    # volumes:
    #   - ../data/db:/var/lib/mysql
    env_file:
      - .env
    command: ./run.sh
  wp:
    build: ${PATH_REQ}wordpress/
    container_name: wp
    depends_on:
      - db
      # - web
    volumes:
      - ../data/wp:/var/www
    networks:
      - docker-network
    restart: always
    env_file:
      - .env
    command: ./run.sh

networks:
  docker-network: {}